---
driver:
  name: vagrant
  customize:
    memory: 512
    cpuexecutioncap: 50

provisioner:
  name: chef_zero

# Let's make it a policy that we'll keep no more than
# 3 major revs of a given platform. That should fall
# close to, or better than, the version support provided by
# the distribution (ex. remove Centos 5 when Centos 8 is added)
platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: centos-7.0
  - name: fedora-21
  - name: fedora-22

suites:
  - name: install
    run_list:
      - recipe[yumgroup::_kitchen_install]
    attributes:
      yum:
        centos:
          group: 'Web Server'
        fedora:
          group: 'web-server'
  - name: upgrade
    run_list:
      - recipe[yumgroup::_kitchen_upgrade]
    attributes:
      yum:
        centos:
          group: 'Web Server'
        fedora:
          group: 'web-server'
  - name: remove
    run_list:
      - recipe[yumgroup::_kitchen_remove]
    attributes:
      yum:
        centos:
          group: 'Web Server'
        fedora:
          group: 'web-server'
