name 'yumgroup'
maintainer 'Mike Morris'
maintainer_email 'michael.m.morris@gmail.com'
license 'BSD-3-Clause'
description 'Installs/Configures yum packages via yum groups'
version '0.7.0'

supports 'redhat', '>= 5.0'
supports 'centos', '>= 5.0'
supports 'fedora', '>= 19.0'
supports 'fedora', '< 22.0'
